export interface GeoInfo {
  countryCode: string;
  countryName: string;
  currency: string;
  currencySymbol: string;
}

export const COUNTRY_CURRENCY_MAP: Record<string, { currency: string; symbol: string; name: string }> = {
  AF: { currency: "AFN", symbol: "؋", name: "Afghanistan" },
  AL: { currency: "ALL", symbol: "L", name: "Albania" },
  DZ: { currency: "DZD", symbol: "دج", name: "Algeria" },
  AO: { currency: "AOA", symbol: "Kz", name: "Angola" },
  AR: { currency: "ARS", symbol: "$", name: "Argentina" },
  AM: { currency: "AMD", symbol: "֏", name: "Armenia" },
  AU: { currency: "AUD", symbol: "A$", name: "Australia" },
  AT: { currency: "EUR", symbol: "€", name: "Austria" },
  AZ: { currency: "AZN", symbol: "₼", name: "Azerbaijan" },
  BH: { currency: "BHD", symbol: "BD", name: "Bahrain" },
  BD: { currency: "BDT", symbol: "৳", name: "Bangladesh" },
  BY: { currency: "BYN", symbol: "Br", name: "Belarus" },
  BE: { currency: "EUR", symbol: "€", name: "Belgium" },
  BJ: { currency: "XOF", symbol: "CFA", name: "Benin" },
  BO: { currency: "BOB", symbol: "Bs", name: "Bolivia" },
  BA: { currency: "BAM", symbol: "KM", name: "Bosnia" },
  BW: { currency: "BWP", symbol: "P", name: "Botswana" },
  BR: { currency: "BRL", symbol: "R$", name: "Brazil" },
  BN: { currency: "BND", symbol: "B$", name: "Brunei" },
  BG: { currency: "BGN", symbol: "лв", name: "Bulgaria" },
  BF: { currency: "XOF", symbol: "CFA", name: "Burkina Faso" },
  BI: { currency: "BIF", symbol: "Fr", name: "Burundi" },
  CV: { currency: "CVE", symbol: "$", name: "Cabo Verde" },
  CM: { currency: "XAF", symbol: "FCFA", name: "Cameroon" },
  CA: { currency: "CAD", symbol: "C$", name: "Canada" },
  CF: { currency: "XAF", symbol: "FCFA", name: "Central African Republic" },
  TD: { currency: "XAF", symbol: "FCFA", name: "Chad" },
  CL: { currency: "CLP", symbol: "$", name: "Chile" },
  CN: { currency: "CNY", symbol: "¥", name: "China" },
  CO: { currency: "COP", symbol: "$", name: "Colombia" },
  KM: { currency: "KMF", symbol: "Fr", name: "Comoros" },
  CG: { currency: "XAF", symbol: "FCFA", name: "Congo" },
  CD: { currency: "CDF", symbol: "Fr", name: "DR Congo" },
  CR: { currency: "CRC", symbol: "₡", name: "Costa Rica" },
  CI: { currency: "XOF", symbol: "CFA", name: "Côte d'Ivoire" },
  HR: { currency: "EUR", symbol: "€", name: "Croatia" },
  CU: { currency: "CUP", symbol: "$", name: "Cuba" },
  CY: { currency: "EUR", symbol: "€", name: "Cyprus" },
  CZ: { currency: "CZK", symbol: "Kč", name: "Czech Republic" },
  DK: { currency: "DKK", symbol: "kr", name: "Denmark" },
  DJ: { currency: "DJF", symbol: "Fr", name: "Djibouti" },
  DO: { currency: "DOP", symbol: "RD$", name: "Dominican Republic" },
  EC: { currency: "USD", symbol: "$", name: "Ecuador" },
  EG: { currency: "EGP", symbol: "£", name: "Egypt" },
  SV: { currency: "USD", symbol: "$", name: "El Salvador" },
  GQ: { currency: "XAF", symbol: "FCFA", name: "Equatorial Guinea" },
  ER: { currency: "ERN", symbol: "Nfk", name: "Eritrea" },
  EE: { currency: "EUR", symbol: "€", name: "Estonia" },
  SZ: { currency: "SZL", symbol: "E", name: "Eswatini" },
  ET: { currency: "ETB", symbol: "Br", name: "Ethiopia" },
  FJ: { currency: "FJD", symbol: "FJ$", name: "Fiji" },
  FI: { currency: "EUR", symbol: "€", name: "Finland" },
  FR: { currency: "EUR", symbol: "€", name: "France" },
  GA: { currency: "XAF", symbol: "FCFA", name: "Gabon" },
  GM: { currency: "GMD", symbol: "D", name: "Gambia" },
  GE: { currency: "GEL", symbol: "₾", name: "Georgia" },
  DE: { currency: "EUR", symbol: "€", name: "Germany" },
  GH: { currency: "GHS", symbol: "₵", name: "Ghana" },
  GR: { currency: "EUR", symbol: "€", name: "Greece" },
  GT: { currency: "GTQ", symbol: "Q", name: "Guatemala" },
  GN: { currency: "GNF", symbol: "Fr", name: "Guinea" },
  GW: { currency: "XOF", symbol: "CFA", name: "Guinea-Bissau" },
  GY: { currency: "GYD", symbol: "$", name: "Guyana" },
  HT: { currency: "HTG", symbol: "G", name: "Haiti" },
  HN: { currency: "HNL", symbol: "L", name: "Honduras" },
  HU: { currency: "HUF", symbol: "Ft", name: "Hungary" },
  IS: { currency: "ISK", symbol: "kr", name: "Iceland" },
  IN: { currency: "INR", symbol: "₹", name: "India" },
  ID: { currency: "IDR", symbol: "Rp", name: "Indonesia" },
  IR: { currency: "IRR", symbol: "﷼", name: "Iran" },
  IQ: { currency: "IQD", symbol: "ع.د", name: "Iraq" },
  IE: { currency: "EUR", symbol: "€", name: "Ireland" },
  IL: { currency: "ILS", symbol: "₪", name: "Israel" },
  IT: { currency: "EUR", symbol: "€", name: "Italy" },
  JM: { currency: "JMD", symbol: "J$", name: "Jamaica" },
  JP: { currency: "JPY", symbol: "¥", name: "Japan" },
  JO: { currency: "JOD", symbol: "JD", name: "Jordan" },
  KZ: { currency: "KZT", symbol: "₸", name: "Kazakhstan" },
  KE: { currency: "KES", symbol: "KSh", name: "Kenya" },
  KW: { currency: "KWD", symbol: "KD", name: "Kuwait" },
  KG: { currency: "KGS", symbol: "с", name: "Kyrgyzstan" },
  LA: { currency: "LAK", symbol: "₭", name: "Laos" },
  LV: { currency: "EUR", symbol: "€", name: "Latvia" },
  LB: { currency: "LBP", symbol: "ل.ل", name: "Lebanon" },
  LS: { currency: "LSL", symbol: "L", name: "Lesotho" },
  LR: { currency: "LRD", symbol: "$", name: "Liberia" },
  LY: { currency: "LYD", symbol: "ل.د", name: "Libya" },
  LT: { currency: "EUR", symbol: "€", name: "Lithuania" },
  LU: { currency: "EUR", symbol: "€", name: "Luxembourg" },
  MG: { currency: "MGA", symbol: "Ar", name: "Madagascar" },
  MW: { currency: "MWK", symbol: "MK", name: "Malawi" },
  MY: { currency: "MYR", symbol: "RM", name: "Malaysia" },
  MV: { currency: "MVR", symbol: "Rf", name: "Maldives" },
  ML: { currency: "XOF", symbol: "CFA", name: "Mali" },
  MT: { currency: "EUR", symbol: "€", name: "Malta" },
  MR: { currency: "MRU", symbol: "UM", name: "Mauritania" },
  MU: { currency: "MUR", symbol: "₨", name: "Mauritius" },
  MX: { currency: "MXN", symbol: "$", name: "Mexico" },
  MD: { currency: "MDL", symbol: "L", name: "Moldova" },
  MN: { currency: "MNT", symbol: "₮", name: "Mongolia" },
  ME: { currency: "EUR", symbol: "€", name: "Montenegro" },
  MA: { currency: "MAD", symbol: "MAD", name: "Morocco" },
  MZ: { currency: "MZN", symbol: "MT", name: "Mozambique" },
  MM: { currency: "MMK", symbol: "K", name: "Myanmar" },
  NA: { currency: "NAD", symbol: "$", name: "Namibia" },
  NP: { currency: "NPR", symbol: "₨", name: "Nepal" },
  NL: { currency: "EUR", symbol: "€", name: "Netherlands" },
  NZ: { currency: "NZD", symbol: "NZ$", name: "New Zealand" },
  NI: { currency: "NIO", symbol: "C$", name: "Nicaragua" },
  NE: { currency: "XOF", symbol: "CFA", name: "Niger" },
  NG: { currency: "NGN", symbol: "₦", name: "Nigeria" },
  MK: { currency: "MKD", symbol: "ден", name: "North Macedonia" },
  NO: { currency: "NOK", symbol: "kr", name: "Norway" },
  OM: { currency: "OMR", symbol: "﷼", name: "Oman" },
  PK: { currency: "PKR", symbol: "₨", name: "Pakistan" },
  PA: { currency: "PAB", symbol: "B/.", name: "Panama" },
  PG: { currency: "PGK", symbol: "K", name: "Papua New Guinea" },
  PY: { currency: "PYG", symbol: "₲", name: "Paraguay" },
  PE: { currency: "PEN", symbol: "S/.", name: "Peru" },
  PH: { currency: "PHP", symbol: "₱", name: "Philippines" },
  PL: { currency: "PLN", symbol: "zł", name: "Poland" },
  PT: { currency: "EUR", symbol: "€", name: "Portugal" },
  QA: { currency: "QAR", symbol: "﷼", name: "Qatar" },
  RO: { currency: "RON", symbol: "lei", name: "Romania" },
  RU: { currency: "RUB", symbol: "₽", name: "Russia" },
  RW: { currency: "RWF", symbol: "Fr", name: "Rwanda" },
  SA: { currency: "SAR", symbol: "﷼", name: "Saudi Arabia" },
  SN: { currency: "XOF", symbol: "CFA", name: "Senegal" },
  RS: { currency: "RSD", symbol: "din", name: "Serbia" },
  SL: { currency: "SLL", symbol: "Le", name: "Sierra Leone" },
  SG: { currency: "SGD", symbol: "S$", name: "Singapore" },
  SK: { currency: "EUR", symbol: "€", name: "Slovakia" },
  SI: { currency: "EUR", symbol: "€", name: "Slovenia" },
  SO: { currency: "SOS", symbol: "Sh", name: "Somalia" },
  ZA: { currency: "ZAR", symbol: "R", name: "South Africa" },
  SS: { currency: "SSP", symbol: "£", name: "South Sudan" },
  ES: { currency: "EUR", symbol: "€", name: "Spain" },
  LK: { currency: "LKR", symbol: "₨", name: "Sri Lanka" },
  SD: { currency: "SDG", symbol: "£", name: "Sudan" },
  SR: { currency: "SRD", symbol: "$", name: "Suriname" },
  SE: { currency: "SEK", symbol: "kr", name: "Sweden" },
  CH: { currency: "CHF", symbol: "Fr", name: "Switzerland" },
  SY: { currency: "SYP", symbol: "£", name: "Syria" },
  TW: { currency: "TWD", symbol: "NT$", name: "Taiwan" },
  TJ: { currency: "TJS", symbol: "SM", name: "Tajikistan" },
  TZ: { currency: "TZS", symbol: "Sh", name: "Tanzania" },
  TH: { currency: "THB", symbol: "฿", name: "Thailand" },
  TG: { currency: "XOF", symbol: "CFA", name: "Togo" },
  TT: { currency: "TTD", symbol: "TT$", name: "Trinidad and Tobago" },
  TN: { currency: "TND", symbol: "DT", name: "Tunisia" },
  TR: { currency: "TRY", symbol: "₺", name: "Turkey" },
  TM: { currency: "TMT", symbol: "T", name: "Turkmenistan" },
  UG: { currency: "UGX", symbol: "Sh", name: "Uganda" },
  UA: { currency: "UAH", symbol: "₴", name: "Ukraine" },
  AE: { currency: "AED", symbol: "د.إ", name: "United Arab Emirates" },
  GB: { currency: "GBP", symbol: "£", name: "United Kingdom" },
  US: { currency: "USD", symbol: "$", name: "United States" },
  UY: { currency: "UYU", symbol: "$U", name: "Uruguay" },
  UZ: { currency: "UZS", symbol: "so'm", name: "Uzbekistan" },
  VE: { currency: "VES", symbol: "Bs.S", name: "Venezuela" },
  VN: { currency: "VND", symbol: "₫", name: "Vietnam" },
  YE: { currency: "YER", symbol: "﷼", name: "Yemen" },
  ZM: { currency: "ZMW", symbol: "ZK", name: "Zambia" },
  ZW: { currency: "ZWL", symbol: "$", name: "Zimbabwe" },
};

export const SORTED_COUNTRIES = Object.entries(COUNTRY_CURRENCY_MAP)
  .map(([code, info]) => ({ code, ...info }))
  .sort((a, b) => a.name.localeCompare(b.name));

let _cached: GeoInfo | null = null;

export const detectGeo = async (): Promise<GeoInfo> => {
  if (_cached) return _cached;
  try {
    const res = await fetch("https://ipapi.co/json/", { signal: AbortSignal.timeout(5000) });
    const data = await res.json();
    const countryCode: string = data.country_code || "NG";
    const info = COUNTRY_CURRENCY_MAP[countryCode];
    _cached = {
      countryCode,
      countryName: info?.name || data.country_name || countryCode,
      currency: info?.currency || data.currency || "NGN",
      currencySymbol: info?.symbol || "",
    };
    return _cached;
  } catch {
    _cached = {
      countryCode: "NG",
      countryName: "Nigeria",
      currency: "NGN",
      currencySymbol: "₦",
    };
    return _cached;
  }
};

export const getCurrencySymbol = (currency: string): string => {
  const entry = Object.values(COUNTRY_CURRENCY_MAP).find(c => c.currency === currency);
  return entry?.symbol || currency;
};
